language: python

dist: bionic

sudo: false
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      sudo: true
    - python: 3.8
      env: TOXENV=py38
      sudo: true
    - python: 3.6
      env: TOXENV=py36
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37
      arch: ppc64le
      sudo: true
    - python: 3.8
      env: TOXENV=py38
      sudo: true
      arch: ppc64le

install:
  - pip install -r requirements.txt
  - python setup.py install
  - travis_retry pip install tox
  - pip install --no-deps -e .
script:
  - travis_retry tox
